# Generated by Django 4.1 on 2022-09-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='added_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
