# Generated by Django 4.1 on 2022-09-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_remove_cartitem_variation_cartitem_variation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_upto', models.PositiveIntegerField()),
                ('shipping_charge', models.PositiveIntegerField()),
            ],
        ),
    ]
