# Generated by Django 4.1 on 2022-09-09 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_added_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='added_time',
            new_name='modified_time',
        ),
    ]
