# Generated by Django 4.1 on 2022-09-14 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_address_options_alter_address_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
