# Generated by Django 4.1 on 2022-09-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_subcategory_tagline_alter_subcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='tagline',
            field=models.TextField(blank=True, max_length=155),
        ),
    ]
