# Generated by Django 4.1 on 2022-09-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_remove_language_tagline_category_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=1255),
        ),
        migrations.AlterField(
            model_name='category',
            name='tagline',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True, max_length=1255),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='tagline',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
