# Generated by Django 4.1 on 2022-09-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_category_description_alter_category_tagline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='discount',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
