# Generated by Django 4.1 on 2022-09-04 06:07

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binding',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from='binding_name', unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from='category_name', unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from='language_name', unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from='subcategory_name', unique=True),
        ),
    ]
