# Generated by Django 4.1 on 2022-09-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_alter_subcategory_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='discount',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
