# Generated by Django 4.1 on 2023-10-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_alter_subcategory_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='readable_bookstore/images/categories'),
        ),
        migrations.AlterField(
            model_name='language',
            name='image',
            field=models.ImageField(blank=True, upload_to='readable_bookstore/images/subcategories'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='readable_bookstore/images/subcategories'),
        ),
    ]
