# Generated by Django 4.1 on 2022-10-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='images/banner')),
                ('title', models.CharField(max_length=255)),
                ('tagline', models.CharField(max_length=255)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
