# Generated by Django 4.1 on 2022-09-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Refunded', 'Refunded'), ('Cancelled', 'Cancelled')], default='Processing', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Placed', 'Placed'), ('Failed', 'Failed'), ('Processing', 'Processing'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
    ]
