# Generated by Django 4.1 on 2022-09-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderproduct_status_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Refunded', 'Refunded'), ('Cancelled', 'Cancelled')], default='Processing', max_length=10),
        ),
    ]
