# Generated by Django 4.1 on 2022-09-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_orderproduct_status_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Returned', 'Returned'), ('Return Confirmed', 'Return Confirmed'), ('Cancelled', 'Cancelled')], default='Processing', max_length=20),
        ),
    ]
