# Generated by Django 4.1 on 2022-09-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orderproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Placed', 'Placed'), ('Failed', 'Failed'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
    ]
