# Generated by Django 4.1 on 2022-09-28 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_coupen_discount_order_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='coupen_discount',
            new_name='coupon_discount',
        ),
    ]
