# Generated by Django 4.1 on 2022-09-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_rename_coupen_discount_order_coupon_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='amount',
            new_name='total',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
