# Generated by Django 4.1 on 2022-09-29 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.payment'),
            preserve_default=False,
        ),
    ]
