# Generated by Django 4.1 on 2022-09-04 08:16

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0007_alter_binding_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from='name', unique=True)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('Publisher', models.CharField(blank=True, default=None, max_length=100)),
                ('release_date', models.DateField(blank=True, default=None, null=True)),
                ('price', models.IntegerField(default=None)),
                ('stock', models.IntegerField(default=None)),
                ('is_available', models.BooleanField(default=True)),
                ('cover_image', models.ImageField(upload_to='images/products')),
                ('image1', models.ImageField(blank=True, upload_to='images/products')),
                ('image2', models.ImageField(blank=True, upload_to='images/products')),
                ('image3', models.ImageField(blank=True, upload_to='images/products')),
                ('description', models.TextField(blank=True, default=None, max_length=2000)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('number_of_pages', models.IntegerField(blank=True, default=None)),
                ('weight', models.IntegerField(blank=True, default=None)),
                ('width', models.IntegerField(blank=True, default=None)),
                ('height', models.IntegerField(blank=True, default=None)),
                ('spine_width', models.IntegerField(blank=True, default=None)),
                ('binding', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.binding')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.language')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.subcategory')),
            ],
        ),
    ]
