# Generated by Django 4.1 on 2022-09-17 17:11

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from='name', unique=True)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('Publisher', models.CharField(blank=True, default=None, max_length=100)),
                ('release_date', models.DateField(blank=True, default=None, null=True)),
                ('price', models.IntegerField(default=None)),
                ('stock', models.IntegerField(default=None)),
                ('is_available', models.BooleanField(default=True)),
                ('cover_image', models.ImageField(upload_to='images/products')),
                ('image1', models.ImageField(blank=True, default=None, null=True, upload_to='images/products')),
                ('image2', models.ImageField(blank=True, default=None, null=True, upload_to='images/products')),
                ('image3', models.ImageField(blank=True, default=None, null=True, upload_to='images/products')),
                ('description', models.TextField(blank=True, default=None, max_length=2000)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('number_of_pages', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('spine_width', models.IntegerField(blank=True, null=True)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.language')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.subcategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_category', models.CharField(choices=[('format', 'format')], max_length=100)),
                ('variation_value', models.CharField(choices=[('paperback', 'Paperback'), ('hardcover', 'Hard Cover')], max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
