# Generated by Django 4.1 on 2022-09-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_price_alter_products_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(choices=[('paperback', 'Paperback'), ('hardcover', 'Hard Cover'), ('ebook', 'Ebook'), ('audiobook', 'Audiobook')], max_length=100),
        ),
    ]
