# Generated by Django 4.1 on 2022-09-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('format', 'format')], max_length=100),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(choices=[('paperback', ' Paperback'), ('hardcover', 'Hard Cover')], max_length=100),
        ),
    ]
