# Generated by Django 4.1 on 2022-09-13 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_variation_variation_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='is_active',
            new_name='is_available',
        ),
    ]
