# Generated by Django 4.1 on 2022-09-13 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_is_active_variation_is_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variation_value',
            new_name='format',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='variation_category',
        ),
    ]
