# Generated by Django 4.1 on 2023-10-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_products_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cover_image',
            field=models.ImageField(upload_to='readable_bookstore/images/products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='readable_bookstore/images/products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='readable_bookstore/images/products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='readable_bookstore/images/products'),
        ),
    ]
